### ISSUE TITLE
+ 

### ISSUE THREAD

**Issue by sequinGore** [Dpeta/pesterchum-alt-servers#10]
i didnt mean to comment???? but uhh how do i download it and get it running?? im not rlly good w techy stuff ;;

**Comment by Dpeta** [comment]
That's valid! You should go to https://github.com/Dpeta/pesterchum-alt-servers/releases and download ```Pesterchum-Alt-Windows-116.zip``` (assuming you're on Windows), and then extract it and run ```pesterchum.exe```.

**Comment by Msr-Shift** [comment]
Uuh, hello I can't get it working too. i think i installed python 2.7 and PyQt4 ( i don't know if i did it right and not forgotten anything), but my PC is 32 bit system (rly old), could this be the problem? Otherwise i don't really know what to do, my other buddies just copied the thing and it's working.
I'm also always used some Russian (my country) recompiled and translated .exe file that automatically did the thing and so i never actually installed ant other thing and don't know what to do :0 Can it be helped?

**Comment by Dpeta** [comment]
Ah, I'm sorry for my late response.
I don't think you did anything wrong, I just hadn't considered that the build would be win-amd64 specific, I'll see if I can get around to making a 32-bit specific build, I think that might require me to set up a seperate 32-bit installation of python though.

**Comment by Dpeta** [comment]
Though, since you said you'd already installed Python 2.7 & PyQt4. You might be able to try just downloading the source code and just running ```python pesterchum.py``` uncompiled.

**Comment by Msr-Shift** [comment]
> Though, since you said you'd already installed Python 2.7 & PyQt4. You might be able to try just downloading the source code and just running `python pesterchum.py` uncompiled.

So... what i need to do that? i kinda struggle with that REALLY much and don't want to fuck up my files or somethin.
Like.. i need to do, in steps: 
download all source code, frop it all in some folder on my PC, and then just run Python pchum. pu that i didn't find on "compiled" version, right? 
Or can i just load this one python PChum.py sctipt and start with just this?

**Comment by Dpeta** [comment]
Nevermind that idea for now, I tried making a win32 build, could you test if it works? :3c (It's in releases)

**Comment by Msr-Shift** [comment]
I... i think it's worked, thanks, but i'm also tried to merge old logs and other saved data (like quirks) and accidentially deleted 4 years of all this stuff so i'm kinda dead now. why i am doing this.
