### ISSUE TITLE
Audio comes out of the wrong device, no way to change it

### ISSUE THREAD

**Issue by GTcreyon** [Dpeta/pesterchum-alt-servers#121]
All audio SFX comes out of my monitor speakers rather than my headphones. Trying to change this in system settings just results in it getting reverted or making no audio at all.

Platform is Linux, specifically EndeavourOS with the KDE Plasma desktop environment.

**Comment by Dpeta** [comment]
Added an option to choose the audio output device, does that fix it? :?c (https://github.com/Dpeta/pesterchum-alt-servers/commit/1d4e34d9e003d8855b1276ce9d3e28e0ccaf506f)

**Comment by GTcreyon** [comment]
That seems ideal! Thank you.

**Comment by GTcreyon** [comment]
That said, in a clone of the repo made a few minutes ago, no audio devices show up.
`WARNING - Can't get audio devices, not using PyQt6 QtMultimedia?`

**Comment by GTcreyon** [comment]
> That said, in a clone of the repo made a few minutes ago, no audio devices show up. `WARNING - Can't get audio devices, not using PyQt6 QtMultimedia?`

`pip install pyqt6` solved it. I'm not familiar with python, is there a way to ensure that PyQt6 is installed as a dependency?

**Comment by Dpeta** [comment]
Valid 🙏
If you didn't have PyQt6 you were running with PyQt5 before, it's probably installed since it's still a KDE Plasma dependency. [Plasma 6](https://community.kde.org/Schedules/Plasma_6) will use Qt6 though as Qt5 is EOL for non-commercial use.

I used a Qt6 exclusive class ([QMediaDevices](https://doc.qt.io/qt-6/qmediadevices.html)) to get the list of audio devices, so it doesn't work with Qt5 rn.

**Comment by Dpeta** [comment]
🐈👍🎉✅
