### ISSUE TITLE
server certificate validation failed

### ISSUE THREAD

**Issue by korjanix** [Dpeta/pesterchum-alt-servers#161]
helloooo 
running on win 10 64-bit system, the error pops up everytime. It worked well a couple of months ago _so I'm not really sure what's might be wrong :'3_ 

I saw some threads about this issue, but they're kinda old and won't even work ig >_< 

![image](https://github.com/Dpeta/pesterchum-alt-servers/assets/155690878/343e949d-547a-4be7-b0fe-8fc02296662a)

**Comment by Dpeta** [comment]
It's cuz windows is bad and [lazy loads root certificates](https://community.letsencrypt.org/t/microsoft-windows-root-certificate-lazy-loading/160389) unfortunately. Your system doesn't have the letsencrypt root certificate, and probably won't load it because browsers don't really rely on the windows cert store anymore. Should probably add a workaround for it.

It didn't appear before because the release had bundled certificates via certifi, those got outdated though. Older version mostly just didn't validate TLS certs or didn't use TLS.

You can fix it by opening pesterchum.xyz with edge in internet explorer mode, it'll automatically download the required root certificate to validate the server's certificate.

Or just use a recent artifact build that does have a recent version of certifi, that'll work for the next year or so: https://github.com/Dpeta/pesterchum-alt-servers/actions/runs/7416518127/artifacts/1148957200

**Comment by korjanix** [comment]
aw that explains everything! thank you.
just checked and these two solutions work well now :3c
