### ISSUE TITLE
Can't change my profile in PESTERCHUM.

### ISSUE THREAD

**Issue by roaufba** [Dpeta/pesterchum-alt-servers#163]
![Screenshot_3](https://github.com/Dpeta/pesterchum-alt-servers/assets/158446020/52763f83-26bf-4d7d-9141-b200ba61983f)
re-entering the application via RAR, since my PC gives an error if I try to open PESTERCHUM through Explorer, it gives me an error when I try to log into my profile. **“Choose an existing profile:”** - I select my profile and click OK, after which a window pops up: **“{my profile} is taken already! Pick a new profile.”** I don’t know how to fix this, I rebooted PESTERCHUM several times, deleted and restored, clicked the “Set this profile as default” button, but nothing helps. please advise what should I do or how to fix the bug.

**Comment by mocchapi** [comment]
you likely already had a pesterchum instance running on that profile in the background. This is a common mistake because by default pesterchum minimizes to tray when you click the [X] close button, so its still running, and only one instance can use a chumhandle at a time.

You can check if this is the case next time you encounter this by looking in the bottom right of your taskbar, there should be a little pesterchum logo. if you dont see it, it may be inside the tray area which you can open with the little [ ^ ] button around that same area. If you right click the little pesterchum you should get the option to close it.
After that, you should be able to log in on your handle again.
