### ISSUE TITLE
handle is not ALLOWED on server

### ISSUE THREAD

**Issue by yekyou** [Dpeta/pesterchum-alt-servers#171]
I apologize in advance if anyone has raised this issue before, I have not found any solution similar to my problem!! =( my nickname might be weird hahah and was banned(?) on the server, however, I am not able to change it, because only two options are available: quit and reconnect(the nickname is hidden in the screenshot). the same thing happens when I try to reconnect. I don't have the ability to open the settings\options or something like that to change my nickname. 
I restarted Pesterchum, making sure that the session of the previous launch was completely completed. I've also tried reinstalling different versions to different computer disks folders. but the server remembers my account in any of the cases and does not allow me to create a new one. how can I change my nickname or create a new account?
![5b9fa0cf-e79d-4163-a640-f91069e55a6d](https://github.com/Dpeta/pesterchum-alt-servers/assets/156468929/67ab63a2-a8c9-438d-a86f-b18a657db5e6)

**Comment by Dpeta** [comment]
Ah yeah that's a thing that can happen if the default handle is namebanned, </3 I should probably look into changing it so it just shows the profile picker if it gets a nick ban response if possible... Pesterchum is structured kinda weirdly since it doesn't show any config options until after it has actually connected.

For now you can either like:
- Remove the default profile manually, it's in pesterchum.js which is in /appdata/local/pesterchum on windows. You can remove the ``, "defaultprofile": "ectoBiologist"``  part.
- Ask a mod to remove the handle ban for a sec so you can change your default profile. Support server link is: https://discord.com/invite/UT2fGAr22q .

**Comment by yekyou** [comment]
thank you very much! I tried the first option and everything worked out!
thanks for the quick feedback and detailed response ^_^
