### ISSUE TITLE
issues with the theme settings not working

### ISSUE THREAD

**Issue by ii7nsomnia7cc** [Dpeta/pesterchum-alt-servers#175]
hi! bit of a fraidycat so im not very confident in joining th support discord for help, so im very sorry if i mess anything up here lol uh. so i wanted to go to the themes to mess around and put something else on, but all i get is this error message and no matter what i try i cant seem to change the theme? not sure if this is just a me issue or not but heres the error

![image](https://github.com/Dpeta/pesterchum-alt-servers/assets/173811846/83155238-a9ae-4320-abd2-97e5572f072a)

**Comment by Dpeta** [comment]
It's valid; That error is only for the remote theme repository, since the current release doesn't have a url included by default. You should still be able to change themes by selecting one on the drop-down menu at the top and then pressing ok.
![image](https://github.com/Dpeta/pesterchum-alt-servers/assets/69427753/9105f5f2-7d4a-4573-98bf-49d3314e212e)

**Comment by ii7nsomnia7cc** [comment]
ohh okay thank you! the icons dont show up for me for some reason, but ill try that!
