### ISSUE TITLE
Can't use my profile

### ISSUE THREAD

**Issue by MarioYellow** [Dpeta/pesterchum-alt-servers#25]
Hi!
So I created a profile, it appears on the userlist and in the app's files too, but something happened or glitched out after i closed the window because I can't log back into the profile because it says "It's (the name) already taken!"

**Comment by Daosp** [comment]
Look in the tray. There should be two Pesterchum icons.
![1](https://user-images.githubusercontent.com/33455315/114910442-98891a80-9e26-11eb-915f-258b8222434e.png)

**Comment by Dpeta** [comment]
Pesterchum's default action on pressing the 'x' is to minimize to your tray, this is configurable in settings. You can also quit Pesterchum completely like so:
![Screenshot_20210419_120005](https://user-images.githubusercontent.com/69427753/115218962-978e0c80-a0f6-11eb-86cd-4956a4a1ad00.png)
![Screenshot_20210419_120046](https://user-images.githubusercontent.com/69427753/115219003-a07ede00-a0f6-11eb-9fa1-39cd599347de.png)

If Pesterchum is still running even though it's not present in your tray then that's not intentional behavior and you should close it via task manager :3c
