### ISSUE TITLE
colors

### ISSUE THREAD

**Issue by psychoticPsilocybin** [Dpeta/pesterchum-alt-servers#26]
since the new update i haven't been able to see any text colors aside from my own, i can see them in memos. but in 1 on 1 i cant 
ive tried resetting my computer closing the program etc.. what should i do?

**Comment by psychoticPsilocybin** [comment]
ok i did a few things its mostly fixed.but the text at the top its still black like, the [CH](chum handle) when the convo begins is still black

**Comment by Dpeta** [comment]
As far as I can tell, the color issue is fixed in v2.1.2 (at least, for me)
I can't tell any difference color-wise between the old pyqt4 version (v1.20): ![Screenshot_20210419_224445](https://user-images.githubusercontent.com/69427753/115301058-3e52c700-a150-11eb-841f-454b10f31509.png) and v2.1.2:
![Screenshot_20210419_224330](https://user-images.githubusercontent.com/69427753/115301067-401c8a80-a150-11eb-8783-c16500560826.png)
(The reason the style is different is because I'm running v1.20 with wine, but that shouldn't matter.)
If you're already running v2.1.2 could you maybe send a screencap? :?c

**Comment by Dpeta** [comment]
Oh wait, I think I see what you mean- It does seem to still be black for some handles.

**Comment by Dpeta** [comment]
Hmm, it seems the the first time you open up a dialog with someone their initials show up as black, at least, that's what it seems like to me. I tested it with an old version and it seems to function the same way there, so, perhaps it's been behaving like that for quite a while.

**Comment by Dpeta** [comment]
It seems that PESTERCHUM:BEGIN is send before color is, so, it'd make sense that the initials wouldn't show up with a color on the first dialogue, as that wouldn't have been communicated yet.
``<> PESTERCHUM:BEGIN``
``<> COLOR >255,0,0``

**Comment by Dpeta** [comment]
The issue of not being able to see direct pester colors at all is a separate issue that was fixed in v2.1.2, btw. See #24
