### ISSUE TITLE
Trying to make a personal IRC server for pesterchum.

### ISSUE THREAD

**Issue by kisatoto** [Dpeta/pesterchum-alt-servers#28]
I'm currently working on a small project for my group of friends and one of things I wanted to do was have our own little network on Pester. I've set up a basic IRC server and can connect to it using Hexchat, however, when I try to connect to it using Pesterchum I get an error saying that the SSL has the wrong version number. 
![image](https://user-images.githubusercontent.com/11702355/116229537-78e9d000-a70b-11eb-9692-56c817e7e879.png)

How would I resolve this?

**Comment by Dpeta** [comment]
Hmmm, I think the "WRONG_VERSION_NUMBER" error can appear in cases even where the SSL/TLS version isn't the issue. For example, I've had the same error when:
- Connecting to a non-SSL port with SSL/TLS.
- Trying to connect through SSL while z-lined. (It'll say that instead of connection closed.)

You could try running Pesterchum from the command line with ``-l debug`` and seeing if you get a more descriptive error that way, or maybe try connecting without SSL/TLS.
