### ISSUE TITLE
Linux system tray notification

### ISSUE THREAD

**Issue by sokoAwen** [Dpeta/pesterchum-alt-servers#32]
On linux the notification that appears when minimizing the application to the system tray cannot be clicked. It will continue to appear because you cannot click it.

THANK YOU SO MUCH FOR MAINTAINING THIS PROJECT >:D

**Comment by Dpeta** [comment]
If you mean this notification: 
![Screenshot_20210512_121651](https://user-images.githubusercontent.com/69427753/117959136-3f1fe880-b30b-11eb-8c93-1ed547a66136.png)
Then I think it should currently be unclickable on all platforms and will keep showing up no matter what. :0c (I may be wrong though-)
It might be useful to add an option to disable the message to settings, since I can imagine it can get quite annoying, I mostly included it because people got confused easily.

& np!!!! >:3c

**Comment by Dpeta** [comment]
Closing for now since I don't think the notification is clickable on most platforms, and clicking it doesn't do anything as far as I'm aware :0
