### ISSUE TITLE
Trouble connecting? - Mac

### ISSUE THREAD

**Issue by diabolicrecreation** [Dpeta/pesterchum-alt-servers#41]
I used to be able to run the old pesterchum fine but now I keep getting an "[Errno 51] Network is unreachable" error code with this version. I have absolutely no idea how to fix this or if it has anything to do with the device being a mac. Any ideas?
<img width="364" alt="Screen Shot 2021-07-02 at 3 47 38 PM" src="https://user-images.githubusercontent.com/86853942/124322140-ee7b7d80-db4c-11eb-8a19-168306b1b389.png">

**Comment by Dpeta** [comment]
Hmmmm, it could be? The mac version seems to be quite buggy. Are you still having this issue? :?c

**Comment by diabolicrecreation** [comment]
Yes, sadly :T I'm not sure if it has to do anything with the port or something like that but I have no clue why the network isn't able to connect.

**Comment by Dpeta** [comment]
Hmm, does connecting via kiwiirc work? :?c https://kiwiirc.com/nextclient/irc.pesterchum.xyz/

**Comment by diabolicrecreation** [comment]
Am I supposed to connect Pesterchum's network to kiwiirc somehow or just open the link and use that?

**Comment by Dpeta** [comment]
You could use the link, but, this was more just 4 testing if connecting worked at all.

I'm not sure what the issue is? If it's because of the client then there's alternative way of setting up pchum on mac (via wine or just running the repo with python). Another possibility is that the common IRC ports are blocked or something, maybe that's something important to rule out first. You could try connecting to irc.pesterchum.xyz with any IRC client :0c
