### ISSUE TITLE
Unable to open pesterchum Linux

### ISSUE THREAD

**Issue by LithRakoon** [Dpeta/pesterchum-alt-servers#75]
Hello i am unable to use pesterchum because it wont open and only throws a few errors.

output of the error: https://hastebin.skyra.pw/ixohohatof.pgsql

i am on fedora 35

**Comment by Dpeta** [comment]
Which release is this? :?c Or are you running from source? :0c

**Comment by LithRakoon** [comment]
Pesterchum Alt. Builds 2022-03-26
PesterchumAlt.-2.2.1-linux64-glibc2.27+.tar.gz

**Comment by Dpeta** [comment]
Tried to reproduce this and the build didn't work on Fedora 35 for me either, though I got a pretty different error: `(Pesterchum:4726): GLib-GIO-ERROR **: 10:39:42.443: Settings schema 'org.gnome.settings-daemon.plugins.xsettings' does not contain a key named 'antialiasing`

That might be a Wayland-related error? That'd explain why it's only affecting Fedora, since it seems to be one of the few distros that's already started using Wayland by default for gnome instead of X. And it seems like PyInstaller has only recently started supporting Wayland with PyQt: https://pyinstaller.org/en/stable/CHANGES.html#id4, old binaries don't seem to support it: https://github.com/pyinstaller/pyinstaller/issues/6483

Since the 2.27+ build was made using a slightly outdated release of PyInstaller, it might not have build with Wayland support. The 2.35 build does, but that one only runs on Fedora 36 because of the glibc version.

I put up a release build on Fedora 35 specifically, so that might be worth trying for now: https://github.com/Dpeta/pesterchum-alt-servers/releases/tag/v2.2.2-rc1, I'm not *certain* the Wayland issue is the same issue as the one you're having, but it could fix a dynamic linking issue too if that was the cause after all.

**Comment by LithRakoon** [comment]
hello! 
the new release didnt work for me but the running the pesterchum executable gives a new error this time
<code>Usage: pesterchum.py [OPTIONS]
Use -h/--help to see the available options.
Logging is configured in logging.ini
/home/niki/Videos/Pesterchum/Pesterchum: symbol lookup error: /lib64/libEGL_mesa.so.0: undefined symbol: wl_proxy_marshal_flags</code>

i have also tested from source and everything works there except the window is very small

**Comment by Dpeta** [comment]
Running from source is probably better than running a build anyway, so if that works then that's good :3 👍, it's tiny because Pesterchum ~~currently~~ doesn't scale with resolution.

Pretty sure that's another wayland-related error though, judging from https://github.com/kovidgoyal/kitty/issues/4760, there might also be some relevant info on https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1005268;msg=19.

I'm not able to reproduce it though, I made a new build on fedora & tested it on an arch+gnome+wayland VM and fedora35's liveiso, and it seems to work on both, even seems to run without qt5-wayland, so presumably the QtWaylandClient-related plugins were collected successfully during build:
![Screenshot_20220413_160422](https://user-images.githubusercontent.com/69427753/163198888-221915b3-5f8a-4318-963f-41dd102c6614.png)

Maybe there's something unique about your setup? :"3 If running from source works it might be a non-issue though.

**Comment by LithRakoon** [comment]
well im using the KDE spin of fedora maybe thats affecting something?
i tested the new release on x11 and it seems to work now, its only broken on wayland now it seems which already an improvement!
![image](https://user-images.githubusercontent.com/41258148/163347834-b1fb6fea-acb0-4585-b927-e7bde1575c95.png)

**Comment by LithRakoon** [comment]
ill close down this issue open a new issue thats specificly for wayland with all the info we gathered here

**Comment by LithRakoon** [comment]
> Running from source is probably better than running a build anyway, so if that works then that's good :3 +1, it's tiny because Pesterchum ~currently~ doesn't scale with resolution.
> 
> Pretty sure that's another wayland-related error though, judging from [kovidgoyal/kitty#4760](https://github.com/kovidgoyal/kitty/issues/4760), there might also be some relevant info on https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1005268;msg=19.
> 
> I'm not able to reproduce it though, I made a new build on fedora & tested it on an arch+gnome+wayland VM and fedora35's liveiso, and it seems to work on both, even seems to run without qt5-wayland, so presumably the QtWaylandClient-related plugins were collected successfully during build: ![Screenshot_20220413_160422](https://user-images.githubusercontent.com/69427753/163198888-221915b3-5f8a-4318-963f-41dd102c6614.png)
> 
> Maybe there's something unique about your setup? :"3 If running from source works it might be a non-issue though.

is this tested gnomes implentation of wayland or x11?
