### ISSUE TITLE
Won't let me use my previous profile

### ISSUE THREAD

**Issue by absolutelybatty** [Dpeta/pesterchum-alt-servers#88]
Every time I try to click my previous user name, it tells me that username is already in use. It's listed already on the "existing profiles" drop down

**Comment by Dpeta** [comment]
If it says it's already in use, it means someone's already on the handle. So either:
a. Another instance of Pesterchum is already running in the background.
b. Someone else is using that handle.

Mybe check with task manager & otherwise just ping any mod in the support server & ask if the handle can be kicked :0c

**Comment by absolutelybatty** [comment]
Turned out to be the latter. Sorry about that

**Comment by Dpeta** [comment]
dw :3 👍🎉
