### ISSUE TITLE
a profile error occurred?

### ISSUE THREAD

**Issue by NappoTapo** [Dpeta/pesterchum-alt-servers#89]
![help](https://user-images.githubusercontent.com/71353116/184520276-f4caa91e-3034-46dc-8f10-5995f6a32b92.png)
this pops up when i first tried to open it. any help?

**Comment by Dpeta** [comment]
That error happens when the client can't load any themes from the themes folder, so probably either:
- [The zip file wasn't extracted](https://support.microsoft.com/en-us/windows/zip-and-unzip-files-f6dde0a7-0fec-8294-e1d3-703ed85e7ebc).
- [pesterchum.exe is separated from the 'themes' folder](https://www.howtogeek.com/436615/how-to-create-desktop-shortcuts-on-windows-10-the-easy-way).

**Comment by NappoTapo** [comment]
oh so i just had to unzip it. thx!

**Comment by Dpeta** [comment]
🐱🎉
