### ISSUE TITLE
can't connect?

### ISSUE THREAD

**Issue by awoken76** [Dpeta/pesterchum-alt-servers#9]
![Annotation 2021-01-01 101236](https://user-images.githubusercontent.com/76843643/103441139-e41e0c80-4c19-11eb-8e06-aed8b4cbcf36.png)

**Comment by Dpeta** [comment]
Ah, that's odd, I'm not sure what the cause could be, and since I don't know how to reproduce the error it'll be hard for me to test anything. Maybe you could try:
* Downloading the ```NO_CONSOLE``` version instead, since the console seems to be mentioned in the error message? (I'm not sure if that'll actually fix anything, but it's probably worth a try.)
* If this is the first time you've installed Pesterchum on your computer, maybe it's something to do with it failing to create the json/js/profile files somehow. Maybe you could try installing the original Pesterchum first, and then trying to run my fork again.
* You could try downloading ```default.Console_debug_version.zip``` from https://github.com/Dpeta/pesterchum-alt-servers/releases/tag/v1.14 instead, it might give a more comprehensive error message.

**Comment by Dpeta** [comment]
Or, alternatively, if it had something to do with the prompt itself, perhaps just running the most recent version without the prompt will work.

**Comment by awoken76** [comment]
uh this time i got a. smaller error message??????

![Capture](https://user-images.githubusercontent.com/76843643/103903412-db21b500-50c9-11eb-8e4d-675d68cd7910.PNG)

**Comment by Dpeta** [comment]
That's quite an odd error, seeing as pesterchum uses PyQt4 and not PyQt5. Line 10 of profile.py reads: ```from PyQt4 import QtGui, QtCore```, not 'PyQt5'. Maybe it's trying to import from the version of Python you have installed instead of the one that's packaged with the freeze? I'm really not sure if that's something that can even happen though.
Seaching the repository's source code finds not a single mention of PyQt5.

**Comment by awoken76** [comment]
im really sorry to keep bothering you :(
i tried uninstalling and reinstalling and got this
![Capture](https://user-images.githubusercontent.com/76843643/104935850-c1118d80-5979-11eb-8a7b-d067c29260a2.PNG)

**Comment by awoken76** [comment]
heres what im looking at if that helps
![Capture2](https://user-images.githubusercontent.com/76843643/104935927-d981a800-5979-11eb-9191-370bbc9d803c.PNG)

**Comment by awoken76** [comment]
okay so i noticed that it's looking for files in D: which i think??? is an external thing??????????

**Comment by Dpeta** [comment]
To be entirely honest, I have absolutely no clue. If it's trying to read a json file perhaps it's some syntax error in a file in your ```\AppData\Local\pesterchum``` folder? Maybe try backing up and temporarily removing the folder as a test. (Your logs are probably also stored in there, so make sure not to just delete it! :3c)

**Comment by awoken76** [comment]
its fixed!!!!!! :3c
